const fs = require('fs');
const path = require('path');
const { google } = require('googleapis');
const auth = require('./auth');
const paths = require('../../paths');

class YouTubeUploader {
    /**
     * Uploads the latest generated video using strict metadata.
     */
    async uploadLatestVideo(workspaceId, videoUrl, customTitle, customDescription) {
        // 1. Check for token
        if (!auth.isAuthenticated(workspaceId)) {
            throw new Error('Not authenticated with YouTube. Please authorize first.');
        }

        const client = await auth.getAuthClient(workspaceId);
        console.log('YouTube: Starting upload...');

        let title = customTitle;
        let description = customDescription;
        let absoluteVideoPath = null;

        if (videoUrl) {
            // Convert relative /videos/... URL to absolute path
            const relPath = videoUrl.replace('http://localhost:5000', '');
            absoluteVideoPath = path.join(paths.publicDir, relPath);
        }

        if (!absoluteVideoPath || !fs.existsSync(absoluteVideoPath)) {
            // 2. Read latest video data as fallback
            const wsIdStr = workspaceId || 'default';
            let LATEST_VIDEO_PATH = path.join(paths.dataDir, `latest_video_${wsIdStr}.json`);
            
            if (!fs.existsSync(LATEST_VIDEO_PATH)) {
                // Fallback for older generations
                LATEST_VIDEO_PATH = path.join(paths.dataDir, `latest_video.json`);
                if (!fs.existsSync(LATEST_VIDEO_PATH)) {
                    throw new Error(`No latest video found to upload for workspace ${wsIdStr}.`);
                }
            }

            const videoData = JSON.parse(fs.readFileSync(LATEST_VIDEO_PATH));
            absoluteVideoPath = videoData.video_path;

            if (!title) title = videoData.title || 'My AI Short';
            if (!description) description = videoData.description || 'Generated by AI Shorts.';
        }

        if (!title) title = 'My AI Short';
        if (!description) description = 'Generated by AI Shorts.';

        // Validate video file exists
        if (!fs.existsSync(absoluteVideoPath)) {
            throw new Error(`Video file not found: ${absoluteVideoPath}`);
        }

        // 3. Prepare Metadata

        // Auto-tag #shorts if vertical (simplistic check or just always for this app)
        // Since we default to 9:16, assume shorts.
        if (!title.toLowerCase().includes('#shorts') && !description.toLowerCase().includes('#shorts')) {
            description += '\n\n#shorts';
        }

        const service = google.youtube('v3');

        // 4. Upload
        try {
            const response = await service.videos.insert({
                auth: client,
                part: 'snippet,status',
                requestBody: {
                    snippet: {
                        title: title.substring(0, 100), // Max 100 chars
                        description: description.substring(0, 5000), // Max 5000 chars
                        categoryId: '22', // People & Blogs (generic default)
                    },
                    status: {
                        privacyStatus: 'public', // Changed from unlisted to public so it appears on the channel
                        selfDeclaredMadeForKids: false
                    }
                },
                media: {
                    body: fs.createReadStream(absoluteVideoPath)
                }
            });

            console.log('YouTube: Upload complete.', response.data);
            return response.data;
        } catch (error) {
            console.error('YouTube Upload API Error:', error.message);
            if (error.message && (error.message.includes('invalid_grant') || error.message.includes('disabled_client'))) {
                auth.clearToken(workspaceId);
                throw new Error("YouTube Authentication Expired or Revoked. Please try uploading again to re-authenticate.");
            }
            throw new Error(`YouTube API Error: ${error.message}`);
        }
    }
}

module.exports = new YouTubeUploader();
