const fs = require('fs');
const path = require('path');
const { google } = require('googleapis');
const auth = require('./auth');

const LATEST_VIDEO_PATH = path.join(__dirname, '../data/latest_video.json');

class YouTubeUploader {
    /**
     * Uploads the latest generated video using strict metadata.
     */
    async uploadLatestVideo(workspaceId) {
        // 1. Check for token
        if (!auth.isAuthenticated(workspaceId)) {
            throw new Error('Not authenticated with YouTube. Please authorize first.');
        }

        const client = await auth.getAuthClient(workspaceId);
        console.log('YouTube: Starting upload...');

        // 2. Read latest video data
        if (!fs.existsSync(LATEST_VIDEO_PATH)) {
            throw new Error('No latest video found to upload.');
        }

        const videoData = JSON.parse(fs.readFileSync(LATEST_VIDEO_PATH));

        // Validate video file exists
        if (!fs.existsSync(videoData.video_path)) {
            throw new Error(`Video file not found: ${videoData.video_path}`);
        }

        // 3. Prepare Metadata
        let title = videoData.title || 'My AI Short';
        let description = videoData.description || 'Generated by AI Shorts.';

        // Auto-tag #shorts if vertical (simplistic check or just always for this app)
        // Since we default to 9:16, assume shorts.
        if (!title.toLowerCase().includes('#shorts') && !description.toLowerCase().includes('#shorts')) {
            description += '\n\n#shorts';
        }

        const service = google.youtube('v3');

        // 4. Upload
        const response = await service.videos.insert({
            auth: client,
            part: 'snippet,status',
            requestBody: {
                snippet: {
                    title: title.substring(0, 100), // Max 100 chars
                    description: description.substring(0, 5000), // Max 5000 chars
                    categoryId: '22', // People & Blogs (generic default)
                },
                status: {
                    privacyStatus: 'public', // Changed from unlisted to public so it appears on the channel
                    selfDeclaredMadeForKids: false
                }
            },
            media: {
                body: fs.createReadStream(videoData.video_path)
            }
        });

        console.log('YouTube: Upload complete.', response.data);
        return response.data;
    }
}

module.exports = new YouTubeUploader();
